# Travis CI configuration
language: d
os: linux
dist: bionic # Ubuntu 18.04 LTS (Bionic Beaver)

# Test against minimum required versions of dmd, gdc and ldc
d:
  - dmd-2.076.1
  - gdc # bionic was selected to make gdc-8.4.0 available
  - ldc-1.6.0

addons:
  apt:
    update: true
    packages:
      - libcurl4-gnutls-dev # required by doveralls to run on bionic

before_install:
  # Workaround until more recent versions of gdc become available through install.sh
  - if [ "$DC" = "gdc" ]; then deactivate; sudo apt-get --assume-yes install gdc; fi

install:
  # Download doveralls to current directory.
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
