# Travis CI configuration
language: d
sudo: false

# Test against latest versions of dmd, gdc and ldc
d:
  - dmd
  - gdc
  - ldc

install:
  # Download doveralls to current directory.
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
