# Travis CI configuration
language: d
os: linux
dist: bionic # Ubuntu 18.04 LTS (Bionic Beaver)

# Test against minimum required versions of dmd and ldc
d:
  - dmd-2.076.1
  - ldc-1.6.0

addons:
  apt:
    packages:
      - libcurl4-gnutls-dev # required by doveralls to run on bionic

install:
  # Download doveralls to current directory.
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.2/doveralls_linux_travis"
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
